// <auto-generated />
using System;
using HotelOS.GatewayApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.GatewayApi.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260520125042_AddAuthRbac")]
    partial class AddAuthRbac
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.GatewayApi.Data.GatewayAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", "audit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Gateway started",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 20, 8, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.ApplicationPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create new booking records",
                            Name = "create_booking"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Update booking details",
                            Name = "update_booking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Delete bookings",
                            Name = "delete_booking"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Manage room inventory and status",
                            Name = "manage_rooms"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Manage system users",
                            Name = "manage_users"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Manage role assignments",
                            Name = "manage_roles"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Manage permission catalog",
                            Name = "manage_permissions"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Create room service orders",
                            Name = "create_orders"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Update room service orders",
                            Name = "update_orders"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Resolve maintenance issues",
                            Name = "resolve_maintenance"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Assign maintenance technicians",
                            Name = "assign_maintenance"
                        },
                        new
                        {
                            Id = 12,
                            Description = "View admin dashboard",
                            Name = "view_dashboard"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Manage payments and billing",
                            Name = "manage_payments"
                        },
                        new
                        {
                            Id = 14,
                            Description = "View and export reports",
                            Name = "view_reports"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Monitor workforce status",
                            Name = "manage_workers"
                        });
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Housekeeper"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Technician"
                        },
                        new
                        {
                            Id = 6,
                            Name = "KitchenStaff"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Super Admin",
                            Email = "admin@hotelos.local",
                            IsActive = true,
                            PasswordHash = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Reception Desk",
                            Email = "reception@hotelos.local",
                            IsActive = true,
                            PasswordHash = "reception123"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Housekeeping Lead",
                            Email = "housekeeping@hotelos.local",
                            IsActive = true,
                            PasswordHash = "house123"
                        });
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", "users");
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 15
                        });
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("users_bridge", "users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.RolePermission", b =>
                {
                    b.HasOne("HotelOS.GatewayApi.Models.ApplicationPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelOS.GatewayApi.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelOS.GatewayApi.Models.UserRole", b =>
                {
                    b.HasOne("HotelOS.GatewayApi.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelOS.GatewayApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
