// Re-export all shared types for components and data layer.
export type { Room, Facility, ApiRoom } from './room';
export type { RoomContextValue } from './context';
export type { SliderSlide } from './slider';
export type {
	DashboardMetric,
	AdminMetric,
	AnalyticsPoint,
	AuditLogRecord,
	AuditLogEntry,
	AuthUser,
	EventLogEntry,
	EventLogRecord,
	AppSetting,
	BookingRecord,
	GuestRecord,
	LoginRequest,
	LoginResponse,
	LoginResponseV2,
	MaintenanceTicket,
	PaymentAnalyticsPoint,
	PaymentStats,
	NotificationCenterItem,
	ReportSummary,
	PermissionName,
	PermissionRecord,
	RefreshTokenResponse,
	RevenuePoint,
	RoleRecord,
	TransactionRecord,
	OrderItem,
	RealtimeNotification,
	UserRole,
	RoomOverview,
	RoomDto,
  CreateRoomDto,
  UpdateRoomDto,
  AmenityDto,
  HotelBranch,
  CreateBranchDto,
  UpdateBranchDto,
  RoomKeyDto,
  MasterKeyDto,
} from './hotelos';
