// <auto-generated />
using System;
using HotelOS.RoomService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.RoomService.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    [Migration("20260612135526_AddRoomKeys")]
    partial class AddRoomKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("room_service")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.RoomService.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("amenities", "room_service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-speed internet access",
                            IconUrl = "/images/amenities/wifi.svg",
                            Name = "WiFi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Coffee machine with complimentary pods",
                            IconUrl = "/images/amenities/coffee.svg",
                            Name = "Coffee Machine"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Climate control system",
                            IconUrl = "/images/amenities/ac.svg",
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Smart TV with streaming services",
                            IconUrl = "/images/amenities/tv.svg",
                            Name = "Smart TV"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Flat-screen television",
                            IconUrl = "/images/amenities/tv.svg",
                            Name = "TV"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Stocked mini bar",
                            IconUrl = "/images/amenities/minibar.svg",
                            Name = "Mini Bar"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Private bathroom",
                            IconUrl = "/images/amenities/bath.svg",
                            Name = "Bath"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Whirlpool bathtub",
                            IconUrl = "/images/amenities/jacuzzi.svg",
                            Name = "Jacuzzi"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Private balcony with view",
                            IconUrl = "/images/amenities/balcony.svg",
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Wheelchair accessible",
                            IconUrl = "/images/amenities/wheelchair.svg",
                            Name = "Wheelchair Access"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Accessible roll-in shower",
                            IconUrl = "/images/amenities/shower.svg",
                            Name = "Roll-in Shower"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Dedicated butler service",
                            IconUrl = "/images/amenities/butler.svg",
                            Name = "Butler Service"
                        });
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber", "Status");

                    b.ToTable("orders", "room_service");
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.MasterKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("master_keys", "room_service");
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("menu_items", "room_service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast set",
                            Price = 18m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Club sandwich",
                            Price = 14m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sparkling water",
                            Price = 4m
                        });
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("GuestCapacity")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("rooms", "room_service");
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.RoomKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IssuedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("room_keys", "room_service");
                });

            modelBuilder.Entity("room_amenities", b =>
                {
                    b.Property<int>("amenity_id")
                        .HasColumnType("integer");

                    b.Property<int>("room_id")
                        .HasColumnType("integer");

                    b.HasKey("amenity_id", "room_id");

                    b.HasIndex("room_id");

                    b.ToTable("room_amenities", "room_service");
                });

            modelBuilder.Entity("room_amenities", b =>
                {
                    b.HasOne("HotelOS.RoomService.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("amenity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelOS.RoomService.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
