// <auto-generated />
using HotelOS.RoomService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.RoomService.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    [Migration("20260520124103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("room_service")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.RoomService.Models.FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber", "Status");

                    b.ToTable("orders", "room_service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuestName = "Amelia Stone",
                            RoomNumber = "101",
                            Status = "Preparing",
                            Total = 24m
                        },
                        new
                        {
                            Id = 2,
                            GuestName = "Daniel Reed",
                            RoomNumber = "207",
                            Status = "Out for delivery",
                            Total = 18m
                        });
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("menu_items", "room_service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast set",
                            Price = 18m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Club sandwich",
                            Price = 14m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sparkling water",
                            Price = 4m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
