// <auto-generated />
using HotelOS.RoomService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.RoomService.Migrations
{
    [DbContext(typeof(RoomDbContext))]
    partial class RoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("room_service")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.RoomService.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("amenities", "room_service");

                    b.HasData(
                        new { Id = 1, Name = "WiFi", IconUrl = "/images/amenities/wifi.svg", Description = "High-speed internet access" },
                        new { Id = 2, Name = "Coffee Machine", IconUrl = "/images/amenities/coffee.svg", Description = "Coffee machine with complimentary pods" },
                        new { Id = 3, Name = "Air Conditioning", IconUrl = "/images/amenities/ac.svg", Description = "Climate control system" },
                        new { Id = 4, Name = "Smart TV", IconUrl = "/images/amenities/tv.svg", Description = "Smart TV with streaming services" },
                        new { Id = 5, Name = "TV", IconUrl = "/images/amenities/tv.svg", Description = "Flat-screen television" },
                        new { Id = 6, Name = "Mini Bar", IconUrl = "/images/amenities/minibar.svg", Description = "Stocked mini bar" },
                        new { Id = 7, Name = "Bath", IconUrl = "/images/amenities/bath.svg", Description = "Private bathroom" },
                        new { Id = 8, Name = "Jacuzzi", IconUrl = "/images/amenities/jacuzzi.svg", Description = "Whirlpool bathtub" },
                        new { Id = 9, Name = "Balcony", IconUrl = "/images/amenities/balcony.svg", Description = "Private balcony with view" },
                        new { Id = 10, Name = "Wheelchair Access", IconUrl = "/images/amenities/wheelchair.svg", Description = "Wheelchair accessible" },
                        new { Id = 11, Name = "Roll-in Shower", IconUrl = "/images/amenities/shower.svg", Description = "Accessible roll-in shower" },
                        new { Id = 12, Name = "Butler Service", IconUrl = "/images/amenities/butler.svg", Description = "Dedicated butler service" }
                    );
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber", "Status");

                    b.ToTable("orders", "room_service");
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("menu_items", "room_service");

                    b.HasData(
                        new { Id = 1, Name = "Breakfast set", Price = 18m },
                        new { Id = 2, Name = "Club sandwich", Price = 14m },
                        new { Id = 3, Name = "Sparkling water", Price = 4m }
                    );
                });

            modelBuilder.Entity("HotelOS.RoomService.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GuestCapacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("rooms", "room_service");
                });

            modelBuilder.Entity("room_amenities", b =>
                {
                    b.Property<int>("amenity_id")
                        .HasColumnType("integer");

                    b.Property<int>("room_id")
                        .HasColumnType("integer");

                    b.HasKey("amenity_id", "room_id");

                    b.HasIndex("room_id");

                    b.ToTable("room_amenities", "room_service");
                });

            modelBuilder.Entity("room_amenities", b =>
                {
                    b.HasOne("HotelOS.RoomService.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("amenity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelOS.RoomService.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
